### PR TITLE
Create skyblock island only on level 1

### PR DESCRIPTION
**Pull request by tenplus1**
This pull has the skyblock island spawn only when player is on level 1 so they can finish dirt challenges.

### CODE REVIEW

**Comment by Ezhh** [comment]
Did anyone confirm why this behaviour was present to begin with? I feel like I do remember people talking about it - something to do with people removing other people's islands?

Also - maybe it should be present when someone selects to restart quests? (The restart option also needs fixing). Then everything should be covered.

**Comment by tenplus1** [comment]
The function that generated the initial skyblock runs on every respawn/join and if air is present it redraws the island, I've moved it into the nil check so it knows player is new, draws island and it never happens again.

**Comment by Ezhh** [comment]
I know what it does, but I'm not sure what the gameplay reasoning for it (if any) was.

**Comment by shivajiva101** [comment]
I'm concerned about this, players take dirt from islands, a simple grief would be to remove the dirt leaving only the quest node. That would leave a player stranded and unable to place a node with this change

**Comment by tenplus1** [comment]
Very true, but Robbie wanted it this way...  Restarting a level using button only kills player and deletes progress on current level.

**Comment by Ezhh** [comment]
That's why I want to understand the reasons before changing it. I really, really dislike this happening on death, but the option for it does still need to be there.

@shivajiva101 If this is only triggered when the player selects to restart the quests, I feel that will address both issues, because at the moment we have a second issue - selecting 'Restart' only puts you back to the start of your current level, and if that isn't level 1, you might not have what you need to continue.

So to me, restart should put you back to level 1 (like the text claims it does!), and reform your island. But simply dying shouldn't reform the island (I found it unplayable because if felt like the game itself was griefing me).

**Comment by Ezhh** [comment]
@tenplus1 Robbie was just responding to my comments and didn't have time to look at it.

**Comment by shivajiva101** [comment]
restarting from level 1 is not catered for, my assumption was a player could place the blocks on the ground and restart, making the quests very easy for the repeat performance. If we want to go this way we will need to add some code to clean the players feats file entry, track their chest placements and strip them of assets to do it properly, even then all their buildings will remain as assets.

**Comment by tenplus1** [comment]
Unless a full restart removes their skyblock and nils their name in the skyblock table forcing a new placement and island generation.

**Comment by shivajiva101** [comment]
I believe the code caters for that option via a conf setting, perhaps it just needs a limit to stop a player filling the map

**Comment by Ezhh** [comment]
I think a restart from level 1 is vital, unless some other method can be found to prevent players getting stuck. It was impossible for my test player to progress after someone stole items, because I was on level 2 and no longer had any way to get wood. You shouldn't need to rely on begging other players to help you in order to progress.

**Comment by Cat5TV** [comment]
Thanks all. I'll be in the admin IRC channel to discuss further. Yes really it boils down to this: I'm too busy this week to "understand" this - just the timing is all. But would love to figure this out for the players' sake, and very much appreciate your taking charge and helping with this, especially with my schedule being what it is right now. Thanks! See you on IRC and we'll make some decisions.

**Comment by shivajiva101** [comment]
That's a good solution, it retains the original functionality till the player has been rewarded a protector which stops any players stealing the dirt nodes and spoiling the game

**Comment by Cat5TV** [comment]
Thanks all! This indeed does sound like a great solution. Cheers @tenplus1 - much appreciated!

**Pull request merged**
